测试开始啦
测试报错
测试结束
2019-04-26 20:27:40,875 -  root - INFO - 测试开始啦 - [logger.py:28 ]
2019-04-26 20:27:40,875 -  root - ERROR - 测试报错 - [logger.py:29 ]
2019-04-26 20:27:40,876 -  root - INFO - 测试结束 - [logger.py:31 ]
2019-04-26 20:29:31,685 -  case - INFO - 测试开始啦 - [logger.py:28 ]
2019-04-26 20:29:31,685 -  case - ERROR - 测试报错 - [logger.py:29 ]
2019-04-26 20:29:31,686 -  case - INFO - 测试结束 - [logger.py:31 ]
2019-04-26 20:32:04,616 -  case - INFO - 测试开始啦 - [logger.py:33 ]
2019-04-26 20:32:04,617 -  case - ERROR - 测试报错 - [logger.py:34 ]
2019-04-26 20:32:04,617 -  case - INFO - 测试结束 - [logger.py:36 ]
